set(CLANG_VERSION "12" CACHE STRING "Version Of Clang")

Message(STATUS "Using Clang Version - ${CLANG_VERSION}.")

if(CLANG_VERSION STREQUAL "10")
  set(CMAKE_C_COMPILER "clang-10")
  set(CMAKE_CXX_COMPILER "clang++-10")
elseif(CLANG_VERSION STREQUAL "11")
  set(CMAKE_C_COMPILER "clang-11")
  set(CMAKE_CXX_COMPILER "clang++-11")
 elseif(CLANG_VERSION STREQUAL "12")
  set(CMAKE_C_COMPILER "clang-12")
  set(CMAKE_CXX_COMPILER "clang++-12")
elseif(CLANG_VERSION STREQUAL "13")
  set(CMAKE_C_COMPILER "clang-13")
  set(CMAKE_CXX_COMPILER "clang++-13")
else()
  MESSAGE(FATAL_ERROR "Minimum Clang Version is clang-10")
endif()

if (BUILD_COVERAGE)
    Message(STATUS "Enabling Build Coverage")
    SET(CLANG_COVERAGE_COMPILE_FLAGS "-fprofile-instr-generate -fcoverage-mapping")
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CLANG_COVERAGE_COMPILE_FLAGS}")
endif ()
